### ISSUE TITLE
[es_ES] Issues regarding "hundreds" grammar + simple typo.

### ISSUE THREAD

**Issue by samuelpx** [aeroo/currency2text#1]
## Grammar Issue

In spanish, there is a slight variation with writing numbers in the hundreds:

"100" is "cien", but whener we have "1XX" and the "X"s are not zeroes, a variation occurs, and it becomes "ciento", so something like €120.00 should translate to "ciento veinte", but currently translates to "cien veint".

## Typo Issue

The previous example also contains a typo in the code, as "twenty" should be "veint**e**", and is currently transcripted as "veint".

The below code should reproduce both issues:

`currency_to_text(120, 'EUR', 'es_ES')`

(I'm still new to this whole github thing, but I was working on the portuguese (pt_BR) inclusion for the library when I found this, since portuguese has the same variation with hundreds, hope this helped, I'll be sending a PR as soon as I'm done)

**Comment by sraps** [comment]
Please check the attached repository!

P.S. Thank you for the bug report. Will be looking for mentioned Portuguese language localization

**Comment by samuelpx** [comment]
Just checked the recent commit, pretty much what I was doing with the pt_BR version, nice work!

Closing note: issue correct in branch commit, thanks!

**Comment by samuelpx** [comment]
Closing note: issue correct in branch commit, thanks
